program: dpp.py
method: grid
parameters:
  mode:
    value: search
  domain:
    value: lsystem
  featurizer:
    value: "Trail"
  search:
    parameters:
      random_seed:
        value: 0
      popn_size:
        value: 100
      n_epochs:
        value: 100
      sim_steps:
        value: 1000
      fit_policy:
        values: [ single, all, first ]
      accept_policy:
        values: [ energy, moment, all ]
      distance_metric:
        value: euclidean
      archive_beta:
        value: 0
      archive_size:
        value: 100
      program_depth:
        value: 4
      length cap:
        value: 10000            # doesn't do anything; only need depth

