program: dpp.py
method: grid
parameters:
  mode:
    value: search
  domain:
    value: lsystem
  x_init:
    values:
      - - "20;F;F~F"
        - "90;F;F~FF"
        - "45;F[+F][-F]FF;F~FF"
        - "60;F+F-F;F~F+FF"
        - "60;F;F~F[+F][-F]F"
        - "90;F-F-F-F;F~F+FF-FF-F-F+F+FF-F-F+F+FF+FF-F"
        - "90;-F;F~F+F-F-F+F"
        - "90;F-F-F-F;F~FF-F-F-F-F-F+F"
        - "90;F-F-F-F;F~FF-F-F-F-FF"
        - "90;F-F-F-F;F~FF-F+F-F-FF"
        - "90;F-F-F-F;F~FF-F--F-F"
        - "90;F-F-F-F;F~F-FF--F-F"
        - "90;F-F-F-F;F~F-F+F-F-F"
        - "20;F;F~F[+F]F[-F]F"
        - "20;F;F~F[+F]F[-F][F]"
        - "20;F;F~FF-[-F+F+F]+[+F-F-F]"
  featurizer:
    parameters:
      disable_last_layer:
        value: true
      softmax_outputs:
        value: false
      sigma:
        values: [ 0, 3, 5, 10 ]
  render:
    parameters:
      step_length:
        value: 4
      render_depth:
        value: 3
      n_rows:
        value: 128
      n_cols:
        value: 128
      vary_color:
        values: [ false, true ]
  search:
    parameters:
      popn_size:
        value: 1000
      epochs:
        value: 200
      update_policy:
        values: [ rr ]
      fit_policy:
        values: [ single, all ]
      accept_policy:
        value: [ energy, moment ]
      length_cap:
        value: 100
