program: run_ant.py
method: grid
parameters:
  mode:
    value: search
  domain:
    value: ant
  featurizer:
    values: [ end, trail ]
  environment:
    values: [ 2d-oriented ]
  maze_name:
    values: [ users-guide, lehman-ecj-11-hard, empty-10x10 ]
  random_seed:
    value: 0
  popn_size:
    value: 150
  n_epochs:
    value: 100
  sim_steps:
    value: 1000
  fit_policy:
    values: [ single, all ]
  accept_policy:
    values: [ energy ]
  distance_metric:
    values: [ euclidean ]
  archive_beta:
    values: [ 0, 1, 5 ]
  archive_size:
    value: 25
  program_depth:
    values: [ 6 ]
  length_cap:
    value: 10000
  step_length:
    value: 0.5
  debug:
    value: true
