program: run_lsys.py
method: grid
parameters:
  mode:
    value: search
  domain:
    value: lsystem
  x_init:
    values:
      - - "20;F;F~F"
        - "90;F;F~FF"
        - "45;F[+F][-F]FF;F~FF"
        - "60;F+F-F;F~F+FF"
        - "60;F;F~F[+F][-F]F"
        - "90;F-F-F-F;F~F+FF-FF-F-F+F+FF-F-F+F+FF+FF-F"
        - "90;-F;F~F+F-F-F+F"
        - "90;F-F-F-F;F~FF-F-F-F-F-F+F"
        - "90;F-F-F-F;F~FF-F-F-F-FF"
        - "90;F-F-F-F;F~FF-F+F-F-FF"
        - "90;F-F-F-F;F~FF-F--F-F"
        - "90;F-F-F-F;F~F-FF--F-F"
        - "90;F-F-F-F;F~F-F+F-F-F"
        - "20;F;F~F[+F]F[-F]F"
        - "20;F;F~F[+F]F[-F][F]"
        - "20;F;F~FF-[-F+F+F]+[+F-F-F]"
  featurizer:
    parameters:
      kind:
        values: [ resnet ]
      disable_last_layer:
        value: true
      softmax_outputs:
        value: false
      sigma:
        value: 3
  render:
    parameters:
      step_length:
        value: 4
      render_depth:
        value: 3
      n_rows:
        value: 128
      n_cols:
        value: 128
      vary_color:
        value: false
  search:
    parameters:
      distance_metric:
        values: [ euclidean, cosine ]
      random_seed:
        value: 0
      popn_size:
        value: 1000
      n_epochs:
        value: 50
      fit_policy:
        values: [ single, all ]
      accept_policy:
        values: [ energy, moment ]
      archive_beta:
        values: [ 0, 1 ]
      archive_size:
        value: 50
      length_cap:
        value: 200
      keep_original:
        value: true
      debug:
        value: true
