program: ns.py
method: grid
metric:
  goal: minimize
  name: "avg sample holdout dist"
parameters:
  disable_last_layer:
    values: [ true, false ]
  softmax_outputs:
    values: [ true, false ]
  train_data:
    value:
      - "20;F;F~F"
      - "90;F;F~FF"
      - "45;F[+F][-F]FF;F~FF"
      - "60;F+F-F;F~F+FF"
      - "60;F;F~F[+F][-F]F"
  holdout_data:
    value:
      - "90;F-F-F-F;F~F+FF-FF-F-F+F+FF-F-F+F+FF+FF-F"
      - "90;-F;F~F+F-F-F+F"
      - "90;F-F-F-F;F~FF-F-F-F-F-F+F"
      - "90;F-F-F-F;F~FF-F-F-F-FF"
      - "90;F-F-F-F;F~FF-F+F-F-FF"
      - "90;F-F-F-F;F~FF-F--F-F"
      - "90;F-F-F-F;F~F-FF--F-F"
      - "90;F-F-F-F;F~F-F+F-F-F"
      - "20;F;F~F[+F]F[-F]F"
      - "20;F;F~F[+F]F[-F][F]"
      - "20;F;F~FF-[-F+F+F]+[+F-F-F]"

  # novelty search hyperparams
  search:
    parameters:
      samples_per_program:
        value: 1
      iters:
        value: 200
      select:
        value: strict
      alpha:
        value: 1
      max_popn_size:
        value: 100
      samples_ratio:
        value: 10
      keep_per_iter:
        value: 10
      length_cap:
        value: 200
      length_penalty_type:
        values: [additive, inverse]
      length_penalty_additive_coeff:
        value: 1e-2
      length_penalty_inverse_coeff:
        value: 10
      ablate_mutator:
        values: [true, false]
      archive_early:
        value: false
      gaussian_blur_sigma:
        value: 3

  # rendering params
  render:
    parameters:
      step_length:
        value: 4
      render_depth:
        value: 3
      n_rows:
        value: 128
      n_cols:
        value: 128