program: ns.py
method: grid
metric:
  goal: minimize
  name: "avg sample holdout dist"
parameters:
  train_data:
    values:
      - - "20;F;F~F"
        - "90;F;F~FF"
        - "45;F[+F][-F]FF;F~FF"
        - "60;F+F-F;F~F+FF"
        - "60;F;F~F[+F][-F]F"
      - - "90;F-F-F-F;F~F+FF-FF-F-F+F+FF-F-F+F+FF+FF-F"
        - "90;-F;F~F+F-F-F+F"
        - "90;F-F-F-F;F~FF-F-F-F-F-F+F"
        - "90;F-F-F-F;F~FF-F-F-F-FF"
        - "90;F-F-F-F;F~FF-F+F-F-FF"
        - "90;F-F-F-F;F~FF-F--F-F"
        - "90;F-F-F-F;F~F-FF--F-F"
        - "90;F-F-F-F;F~F-F+F-F-F"
        - "20;F;F~F[+F]F[-F]F"
        - "20;F;F~F[+F]F[-F][F]"
        - "20;F;F~FF-[-F+F+F]+[+F-F-F]"
  holdout_data:
    value:
      - "90;F-F-F-F;F~F+FF-FF-F-F+F+FF-F-F+F+FF+FF-F"
      - "90;-F;F~F+F-F-F+F"
      - "90;F-F-F-F;F~FF-F-F-F-F-F+F"
      - "90;F-F-F-F;F~FF-F-F-F-FF"
      - "90;F-F-F-F;F~FF-F+F-F-FF"
      - "90;F-F-F-F;F~FF-F--F-F"
      - "90;F-F-F-F;F~F-FF--F-F"
      - "90;F-F-F-F;F~F-F+F-F-F"
      - "20;F;F~F[+F]F[-F]F"
      - "20;F;F~F[+F]F[-F][F]"
      - "20;F;F~FF-[-F+F+F]+[+F-F-F]"

  simplify:
    values: [true, false]

  featurizer:
    parameters:
      disable_last_layer:
        value: true
      softmax_outputs:
        value: false
      sigma:
        values: [0., 0.5, 1.0, 2.0]

  # novelty search hyperparams
  search:
    parameters:
      samples_per_program:
        value: 1
      iters:
        value: 200
      select:
        values: [strict, weighted]
      alpha:
        value: 1
      max_popn_size:
        value: 100
      samples_ratio:
        value: 10
      keep_per_iter:
        value: 10
      length_cap:
        value: 200
      length_penalty_type:
        value: additive
      length_penalty_additive_coeff:
        value: 0
#        distribution: log_uniform_values
#          min: 0.0001
#          max: 0.1
      length_penalty_inverse_coeff:
        value: 50
      ablate_mutator:
        value: false
      archive_early:
        value: false

  # rendering params
  render:
    parameters:
      step_length:
        value: 4
      render_depth:
        value: 3
      n_rows:
        value: 128
      n_cols:
        value: 128
      vary_color:
        values: [true, false]