simplify: false
train_data:
  - "20;F;F~F"
  - "90;F;F~FF"
  - "45;F[+F][-F]FF;F~FF"
  - "60;F+F-F;F~F+FF"
  - "60;F;F~F[+F][-F]F"

search:
  samples_per_program: 1
  iters: 2
  select: strict
  alpha: 1
  max_popn_size: 10
  samples_ratio: 3
  keep_per_iter: 2  # archiving rate

  # length penalties
  length_cap: 200
  length_penalty_type: additive
  length_penalty_inverse_coeff: 50
  length_penalty_additive_coeff: 0

  # heuristics
  ablate_mutator: false
  archive_early: false

featurizer:
  disable_last_layer: true
  softmax_outputs: false
  sigma: 3

render:
  step_length: 4
  render_depth: 3
  n_rows: 128
  n_cols: 128
  vary_color: True