#!/bin/bash
#SBATCH -J agent                           # Job name
#SBATCH -o agent-%j.out                    # output file (%j expands to jobID)
#SBATCH -e agent-%j.err                    # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                      # Request status by email 
#SBATCH --mail-user=djl328@cornell.edu       # Email address to send results to
#SBATCH -N 1                                 # Total number of nodes requested
#SBATCH -n 1                                # Total number of cores requested
#SBATCH --get-user-env                       # retrieve the users login environment
#SBATCH --mem=64000                         # server memory requested (per node)
#SBATCH -t 168:00:00                          # Time limit (hh:mm:ss)
#SBATCH --partition=ellis                    # Request partition
#SBATCH --gres=gpu:1                         # Request GPU
/home/djl328/prob-repl/slurm/agent.sh
